# This can be used to create Fedora container disk image
# Download URL: https://download.fedoraproject.org/pub/fedora-secondary/releases/39/Cloud/ppc64le/images/Fedora-Cloud-Base-39-1.5.ppc64le.qcow2

FROM scratch

COPY --chown=107:107 --chmod=440 Fedora-Cloud-Base-39-1.5.ppc64le.qcow2 /disk/
